plugins {
    id 'com.android.application'
}

android {
    namespace 'com.astropyrg.game'
    compileSdk 35

    defaultConfig {
        applicationId 'com.astropyrg.game'
        minSdk 24
        targetSdk 35
        versionCode 1
        versionName '0.1-test'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
